export class CovFormEntity {
    id: number;
    creationDate: Date;
    identificationUser: number;
    hasSymptoms: string;
    identificationUserCar: string;
    creationDateF: Date;
    symptomsDate: Date;
    descripSymptims: string;
    concatPerson: string;
    parentsPerson: string;
    cuarentDate: Date;
    famBusiness: string;
    famParents: string;
    documentHos: string;
    active: boolean;
    Name: string;
    company: string; 
    typeDocument: string;
    position: string;
    bossName: string;
    eps: string;
    direction: string;
    phone: string;
    mobile: string;
    email: string;
    placeSymptoms: string;
    statedAnswer: string;
    publicAnswer: string;
    city: string;
    cityId: number;
    countryId:number;
    departmentId:number;
    positions:string;
    dateArea: string;
    contract: string;
    segment: string;
    customer: string;
    statusHealthPunctual: string;
    costCenter: string;
    typeCase: string;
    scheduledAppointment: string;
    dateAppointment: string;
    proofCovid: string;
    dateExecutionProof: string;
    resultProof: string;
    dateNotificationResult: string;
    noApply: string;
    dateSecondProof: string;
    dateExecutionSecondProof: string;
    resultSecondProof: string;
    dateNotificationResultSecond: string;
    segmentResult: string;
    dateThirdProof: string;
    dateExecutionThirdProof: string;
    resultThirdProof: string;
    dateNotificationResultThird: string;
    followUp: string;
    status: string;
    dateReinstate: string;
    observationDelivery: string;
    timeIsolation: string;
    observationWorking: string;
    dayIsolation: string;
    dayInability: string;
    totalDayIsolation: string;
    consolidatedWork: string;
    statusHealth: string;
    siegeEpimiodological: string;
    observation: string;
    hospitalization: string;
    dateProofOne: string;
    dateInitiation: string;
    daysTotal: string;
    totalInfo: string;
    vacunation: string;
    statusWokin:string;


    constructor() { }
}